version: "3.9"

services:
  web:
    build: .
    container_name: drf_web
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles   # ✅ 추가
    ports:
      - "8000:8000"
    env_file:
      - .env
