version: "3.9"

services:
  web:
    build: .
    container_name: drf_web
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    env_file:
      - .env.prod
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:1.25
    container_name: drf_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/staticfiles
      - ./mediafiles:/mediafiles
    depends_on:
      - web
